// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi2G5vKR67aGJ-munbOMbg-lN5F8QKVTA',
    appId: '1:1021241624764:web:6e03c42e190c0ae3fe68b9',
    messagingSenderId: '1021241624764',
    projectId: 'eventcom-8ae4a',
    authDomain: 'eventcom2.firebaseapp.com',
    storageBucket: 'eventcom2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQq1z7JzcczTthf35m6Q9X651BgEeXIEY',
    appId: '1:792604487469:android:457e03085392d9f9202da4',
    messagingSenderId: '792604487469',
    projectId: 'eventcom-8ae4a',
    storageBucket: 'com.example.eventcom',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQq1z7JzcczTthf35m6Q9X651BgEeXIEY',
    appId: '1:792604487469:android:457e03085392d9f9202da4',
    messagingSenderId: '792604487469',
    projectId: 'eventcom-8ae4a',
    storageBucket: 'eventcom2.appspot.com',
    iosClientId:
        '1021241624764-fikh81mg18jkmn2p4ejl2imfceifb6ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventcom',
  );
}
